/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddImageLayerResponse {
    #[serde(rename = "node")]
    pub node: uuid::Uuid,
}

impl AddImageLayerResponse {
    pub fn new(node: uuid::Uuid) -> AddImageLayerResponse {
        AddImageLayerResponse { node }
    }
}
