/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEventOneOf8 {
    #[serde(rename = "event")]
    pub event: Event,
}

impl AppEventOneOf8 {
    pub fn new(event: Event) -> AppEventOneOf8 {
        AppEventOneOf8 { event }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "projectClosed")]
    ProjectClosed,
}

impl Default for Event {
    fn default() -> Event {
        Self::ProjectClosed
    }
}
