/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEventOneOf5 {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: models::JobStatus,
    #[serde(rename = "event")]
    pub event: Event,
}

impl AppEventOneOf5 {
    pub fn new(id: String, status: models::JobStatus, event: Event) -> AppEventOneOf5 {
        AppEventOneOf5 {
            error: None,
            id,
            status,
            event,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "jobFinished")]
    JobFinished,
}

impl Default for Event {
    fn default() -> Event {
        Self::JobFinished
    }
}
