/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEventOneOf13 {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "scope")]
    pub scope: String,
    #[serde(rename = "event")]
    pub event: Event,
}

impl AppEventOneOf13 {
    pub fn new(message: String, scope: String, event: Event) -> AppEventOneOf13 {
        AppEventOneOf13 {
            message,
            scope,
            event,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "error")]
    Error,
}

impl Default for Event {
    fn default() -> Event {
        Self::Error
    }
}
