/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEventOneOf12 {
    #[serde(rename = "downloads")]
    pub downloads: Vec<models::DownloadProgress>,
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::JobSummary>,
    #[serde(rename = "event")]
    pub event: Event,
}

impl AppEventOneOf12 {
    pub fn new(
        downloads: Vec<models::DownloadProgress>,
        jobs: Vec<models::JobSummary>,
        event: Event,
    ) -> AppEventOneOf12 {
        AppEventOneOf12 {
            downloads,
            jobs,
            event,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "snapshot")]
    Snapshot,
}

impl Default for Event {
    fn default() -> Event {
        Self::Snapshot
    }
}
