/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEventOneOf2 {
    #[serde(rename = "epoch")]
    pub epoch: u64,
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "op")]
    pub op: Box<models::Op>,
}

impl AppEventOneOf2 {
    pub fn new(epoch: u64, event: Event, op: models::Op) -> AppEventOneOf2 {
        AppEventOneOf2 {
            epoch,
            event,
            op: Box::new(op),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "opRedone")]
    OpRedone,
}

impl Default for Event {
    fn default() -> Event {
        Self::OpRedone
    }
}
