/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEventOneOf9 {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "target")]
    pub target: Box<models::LlmTarget>,
}

impl AppEventOneOf9 {
    pub fn new(event: Event, target: models::LlmTarget) -> AppEventOneOf9 {
        AppEventOneOf9 {
            event,
            target: Box::new(target),
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "llmLoaded")]
    LlmLoaded,
}

impl Default for Event {
    fn default() -> Event {
        Self::LlmLoaded
    }
}
