/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AppEvent {
    AppEventOneOf(Box<models::AppEventOneOf>),
    AppEventOneOf1(Box<models::AppEventOneOf1>),
    AppEventOneOf2(Box<models::AppEventOneOf2>),
    AppEventOneOf3(Box<models::AppEventOneOf3>),
    AppEventOneOf4(Box<models::AppEventOneOf4>),
    AppEventOneOf5(Box<models::AppEventOneOf5>),
    AppEventOneOf6(Box<models::AppEventOneOf6>),
    AppEventOneOf7(Box<models::AppEventOneOf7>),
    AppEventOneOf8(Box<models::AppEventOneOf8>),
    AppEventOneOf9(Box<models::AppEventOneOf9>),
    AppEventOneOf10(Box<models::AppEventOneOf10>),
    AppEventOneOf11(Box<models::AppEventOneOf11>),
    AppEventOneOf12(Box<models::AppEventOneOf12>),
    AppEventOneOf13(Box<models::AppEventOneOf13>),
}

impl Default for AppEvent {
    fn default() -> Self {
        Self::AppEventOneOf(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "error")]
    Error,
}

impl Default for Event {
    fn default() -> Event {
        Self::Error
    }
}
