/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppEventOneOf3 {
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: String,
}

impl AppEventOneOf3 {
    pub fn new(event: Event, id: String, kind: String) -> AppEventOneOf3 {
        AppEventOneOf3 { event, id, kind }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "jobStarted")]
    JobStarted,
}

impl Default for Event {
    fn default() -> Event {
        Self::JobStarted
    }
}
