/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodexDeviceLogin {
    #[serde(rename = "intervalSeconds")]
    pub interval_seconds: u64,
    #[serde(rename = "loginId")]
    pub login_id: String,
    #[serde(rename = "timeoutSeconds")]
    pub timeout_seconds: u64,
    #[serde(rename = "userCode")]
    pub user_code: String,
    #[serde(rename = "verificationUrl")]
    pub verification_url: String,
}

impl CodexDeviceLogin {
    pub fn new(
        interval_seconds: u64,
        login_id: String,
        timeout_seconds: u64,
        user_code: String,
        verification_url: String,
    ) -> CodexDeviceLogin {
        CodexDeviceLogin {
            interval_seconds,
            login_id,
            timeout_seconds,
            user_code,
            verification_url,
        }
    }
}
