/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodexDeviceLoginStatus {
    #[serde(
        rename = "accountId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_id: Option<Option<String>>,
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
    #[serde(rename = "loginId")]
    pub login_id: String,
    #[serde(rename = "status")]
    pub status: models::CodexAuthAttemptStatus,
}

impl CodexDeviceLoginStatus {
    pub fn new(login_id: String, status: models::CodexAuthAttemptStatus) -> CodexDeviceLoginStatus {
        CodexDeviceLoginStatus {
            account_id: None,
            error: None,
            login_id,
            status,
        }
    }
}
