/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodexAuthStatus {
    #[serde(
        rename = "accountId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_id: Option<Option<String>>,
    #[serde(
        rename = "login",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub login: Option<Option<Box<models::CodexDeviceLoginStatus>>>,
    #[serde(rename = "signedIn")]
    pub signed_in: bool,
}

impl CodexAuthStatus {
    pub fn new(signed_in: bool) -> CodexAuthStatus {
        CodexAuthStatus {
            account_id: None,
            login: None,
            signed_in,
        }
    }
}
