/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigPatch : Sparse patch for `koharu_app::AppConfig`. Missing fields mean \"leave as-is\". The `providers` field, if present, replaces the whole provider list — we do not merge by id because ordering is meaningful.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigPatch {
    #[serde(
        rename = "http",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub http: Option<Option<Box<models::HttpConfigPatch>>>,
    #[serde(
        rename = "pipeline",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pipeline: Option<Option<Box<models::PipelineConfigPatch>>>,
    /// If present, replaces the entire list. Api_key values of `\"[REDACTED]\"` are interpreted as \"leave the existing secret alone\".
    #[serde(
        rename = "providers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub providers: Option<Option<Vec<models::ProviderPatch>>>,
}

impl ConfigPatch {
    /// Sparse patch for `koharu_app::AppConfig`. Missing fields mean \"leave as-is\". The `providers` field, if present, replaces the whole provider list — we do not merge by id because ordering is meaningful.
    pub fn new() -> ConfigPatch {
        ConfigPatch {
            http: None,
            pipeline: None,
            providers: None,
        }
    }
}
