/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePagesFromPathsRequest {
    #[serde(rename = "paths")]
    pub paths: Vec<String>,
    #[serde(rename = "replace", skip_serializing_if = "Option::is_none")]
    pub replace: Option<bool>,
}

impl CreatePagesFromPathsRequest {
    pub fn new(paths: Vec<String>) -> CreatePagesFromPathsRequest {
        CreatePagesFromPathsRequest {
            paths,
            replace: None,
        }
    }
}
