/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePagesResponse {
    #[serde(rename = "pages")]
    pub pages: Vec<uuid::Uuid>,
}

impl CreatePagesResponse {
    pub fn new(pages: Vec<uuid::Uuid>) -> CreatePagesResponse {
        CreatePagesResponse { pages }
    }
}
