/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataConfig {
    #[serde(rename = "path")]
    pub path: String,
}

impl DataConfig {
    pub fn new(path: String) -> DataConfig {
        DataConfig { path }
    }
}
