/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataConfig {
    /// Optional model-library override. `None` uses `{path}/models`.
    #[serde(
        rename = "models_path",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub models_path: Option<Option<String>>,
    #[serde(rename = "path")]
    pub path: String,
}

impl DataConfig {
    pub fn new(path: String) -> DataConfig {
        DataConfig {
            models_path: None,
            path,
        }
    }
}
