/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadStatusOneOf3 {
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "status")]
    pub status: Status,
}

impl DownloadStatusOneOf3 {
    pub fn new(reason: String, status: Status) -> DownloadStatusOneOf3 {
        DownloadStatusOneOf3 { reason, status }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Failed
    }
}
