/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadStatusOneOf {
    #[serde(rename = "status")]
    pub status: Status,
}

impl DownloadStatusOneOf {
    pub fn new(status: Status) -> DownloadStatusOneOf {
        DownloadStatusOneOf { status }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "started")]
    Started,
}

impl Default for Status {
    fn default() -> Status {
        Self::Started
    }
}
