/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DownloadStatus {
    DownloadStatusOneOf(Box<models::DownloadStatusOneOf>),
    DownloadStatusOneOf1(Box<models::DownloadStatusOneOf1>),
    DownloadStatusOneOf2(Box<models::DownloadStatusOneOf2>),
    DownloadStatusOneOf3(Box<models::DownloadStatusOneOf3>),
}

impl Default for DownloadStatus {
    fn default() -> Self {
        Self::DownloadStatusOneOf(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Failed
    }
}
