/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EngineCatalogEntry {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "produces")]
    pub produces: Vec<String>,
}

impl EngineCatalogEntry {
    pub fn new(id: String, name: String, produces: Vec<String>) -> EngineCatalogEntry {
        EngineCatalogEntry { id, name, produces }
    }
}
