/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EngineCatalog {
    #[serde(rename = "detectors")]
    pub detectors: Vec<models::EngineCatalogEntry>,
    #[serde(rename = "fontDetectors")]
    pub font_detectors: Vec<models::EngineCatalogEntry>,
    #[serde(rename = "inpainters")]
    pub inpainters: Vec<models::EngineCatalogEntry>,
    #[serde(rename = "ocr")]
    pub ocr: Vec<models::EngineCatalogEntry>,
    #[serde(rename = "renderers")]
    pub renderers: Vec<models::EngineCatalogEntry>,
    #[serde(rename = "segmenters")]
    pub segmenters: Vec<models::EngineCatalogEntry>,
    #[serde(rename = "translators")]
    pub translators: Vec<models::EngineCatalogEntry>,
}

impl EngineCatalog {
    pub fn new(
        detectors: Vec<models::EngineCatalogEntry>,
        font_detectors: Vec<models::EngineCatalogEntry>,
        inpainters: Vec<models::EngineCatalogEntry>,
        ocr: Vec<models::EngineCatalogEntry>,
        renderers: Vec<models::EngineCatalogEntry>,
        segmenters: Vec<models::EngineCatalogEntry>,
        translators: Vec<models::EngineCatalogEntry>,
    ) -> EngineCatalog {
        EngineCatalog {
            detectors,
            font_detectors,
            inpainters,
            ocr,
            renderers,
            segmenters,
            translators,
        }
    }
}
