/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorEvent {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "scope")]
    pub scope: String,
}

impl ErrorEvent {
    pub fn new(message: String, scope: String) -> ErrorEvent {
        ErrorEvent { message, scope }
    }
}
