/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportProjectResponse {
    #[serde(rename = "count")]
    pub count: u32,
    #[serde(rename = "path")]
    pub path: String,
}

impl ExportProjectResponse {
    pub fn new(count: u32, path: String) -> ExportProjectResponse {
        ExportProjectResponse {
            count,
            path,
        }
    }
}

