/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExportFormat {
    #[serde(rename = "khr")]
    Khr,
    #[serde(rename = "psd")]
    Psd,
    #[serde(rename = "rendered")]
    Rendered,
    #[serde(rename = "inpainted")]
    Inpainted,
}

impl std::fmt::Display for ExportFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Khr => write!(f, "khr"),
            Self::Psd => write!(f, "psd"),
            Self::Rendered => write!(f, "rendered"),
            Self::Inpainted => write!(f, "inpainted"),
        }
    }
}

impl Default for ExportFormat {
    fn default() -> ExportFormat {
        Self::Khr
    }
}
