/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FontFaceInfo {
    #[serde(rename = "cached")]
    pub cached: bool,
    #[serde(
        rename = "category",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub category: Option<Option<String>>,
    #[serde(rename = "familyName")]
    pub family_name: String,
    #[serde(rename = "postScriptName")]
    pub post_script_name: String,
    #[serde(rename = "source")]
    pub source: models::FontSource,
}

impl FontFaceInfo {
    pub fn new(
        cached: bool,
        family_name: String,
        post_script_name: String,
        source: models::FontSource,
    ) -> FontFaceInfo {
        FontFaceInfo {
            cached,
            category: None,
            family_name,
            post_script_name,
            source,
        }
    }
}
