/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoogleFontCatalog {
    #[serde(rename = "fonts")]
    pub fonts: Vec<models::GoogleFontEntry>,
}

impl GoogleFontCatalog {
    pub fn new(fonts: Vec<models::GoogleFontEntry>) -> GoogleFontCatalog {
        GoogleFontCatalog { fonts }
    }
}
