/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoogleFontVariant {
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "style")]
    pub style: String,
    #[serde(rename = "weight")]
    pub weight: u32,
}

impl GoogleFontVariant {
    pub fn new(filename: String, style: String, weight: u32) -> GoogleFontVariant {
        GoogleFontVariant {
            filename,
            style,
            weight,
        }
    }
}
