/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoogleFontEntry {
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "family")]
    pub family: String,
    #[serde(rename = "subsets")]
    pub subsets: Vec<String>,
    #[serde(rename = "variants")]
    pub variants: Vec<models::GoogleFontVariant>,
}

impl GoogleFontEntry {
    pub fn new(
        category: String,
        family: String,
        subsets: Vec<String>,
        variants: Vec<models::GoogleFontVariant>,
    ) -> GoogleFontEntry {
        GoogleFontEntry {
            category,
            family,
            subsets,
            variants,
        }
    }
}
