/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpConfigPatch {
    #[serde(
        rename = "connectTimeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub connect_timeout: Option<Option<u64>>,
    #[serde(
        rename = "maxRetries",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_retries: Option<Option<u32>>,
    #[serde(
        rename = "readTimeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub read_timeout: Option<Option<u64>>,
}

impl HttpConfigPatch {
    pub fn new() -> HttpConfigPatch {
        HttpConfigPatch {
            connect_timeout: None,
            max_retries: None,
            read_timeout: None,
        }
    }
}
