/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpConfig {
    #[serde(rename = "connect_timeout", skip_serializing_if = "Option::is_none")]
    pub connect_timeout: Option<u64>,
    #[serde(rename = "max_retries", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<u32>,
    #[serde(rename = "read_timeout", skip_serializing_if = "Option::is_none")]
    pub read_timeout: Option<u64>,
}

impl HttpConfig {
    pub fn new() -> HttpConfig {
        HttpConfig {
            connect_timeout: None,
            max_retries: None,
            read_timeout: None,
        }
    }
}
