/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageData {
    /// Hex-encoded blake3 hash of an immutable blob.
    #[serde(rename = "blob")]
    pub blob: String,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    #[serde(rename = "naturalHeight")]
    pub natural_height: u32,
    #[serde(rename = "naturalWidth")]
    pub natural_width: u32,
    #[serde(rename = "opacity", skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f32>,
    /// Role tags differentiate source / inpainted / rendered / user-imported images. Role is immutable on an existing node — switching roles = delete + add.
    #[serde(rename = "role")]
    pub role: models::ImageRole,
}

impl ImageData {
    pub fn new(
        blob: String,
        natural_height: u32,
        natural_width: u32,
        role: models::ImageRole,
    ) -> ImageData {
        ImageData {
            blob,
            name: None,
            natural_height,
            natural_width,
            opacity: None,
            role,
        }
    }
}
