/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageRole {
    #[serde(rename = "source")]
    Source,
    #[serde(rename = "inpainted")]
    Inpainted,
    #[serde(rename = "rendered")]
    Rendered,
    #[serde(rename = "custom")]
    Custom,
}

impl std::fmt::Display for ImageRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Source => write!(f, "source"),
            Self::Inpainted => write!(f, "inpainted"),
            Self::Rendered => write!(f, "rendered"),
            Self::Custom => write!(f, "custom"),
        }
    }
}

impl Default for ImageRole {
    fn default() -> ImageRole {
        Self::Source
    }
}
