/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobFinishedEvent {
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: models::JobStatus,
}

impl JobFinishedEvent {
    pub fn new(id: String, status: models::JobStatus) -> JobFinishedEvent {
        JobFinishedEvent {
            error: None,
            id,
            status,
        }
    }
}
