/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobWarningEvent : A non-fatal step failure during a pipeline run. The pipeline recovers by skipping the rest of the current page's steps and moving on to the next page; the UI accumulates these into a list during the job.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobWarningEvent {
    #[serde(rename = "jobId")]
    pub job_id: String,
    #[serde(rename = "message")]
    pub message: String,
    /// 0-based page index where the failure happened.
    #[serde(rename = "pageIndex")]
    pub page_index: u32,
    /// Engine id (e.g. `\"lama-manga\"`) of the step that failed.
    #[serde(rename = "stepId")]
    pub step_id: String,
    #[serde(rename = "totalPages")]
    pub total_pages: u32,
}

impl JobWarningEvent {
    /// A non-fatal step failure during a pipeline run. The pipeline recovers by skipping the rest of the current page's steps and moving on to the next page; the UI accumulates these into a list during the job.
    pub fn new(
        job_id: String,
        message: String,
        page_index: u32,
        step_id: String,
        total_pages: u32,
    ) -> JobWarningEvent {
        JobWarningEvent {
            job_id,
            message,
            page_index,
            step_id,
            total_pages,
        }
    }
}
