/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjectsResponse {
    #[serde(rename = "projects")]
    pub projects: Vec<models::ProjectSummary>,
}

impl ListProjectsResponse {
    pub fn new(projects: Vec<models::ProjectSummary>) -> ListProjectsResponse {
        ListProjectsResponse { projects }
    }
}
