/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDownloadsResponse {
    #[serde(rename = "downloads")]
    pub downloads: Vec<models::DownloadProgress>,
}

impl ListDownloadsResponse {
    pub fn new(downloads: Vec<models::DownloadProgress>) -> ListDownloadsResponse {
        ListDownloadsResponse { downloads }
    }
}
