/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOperationsResponse {
    #[serde(rename = "operations")]
    pub operations: Vec<models::JobSummary>,
}

impl ListOperationsResponse {
    pub fn new(operations: Vec<models::JobSummary>) -> ListOperationsResponse {
        ListOperationsResponse { operations }
    }
}
