/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LlmProviderCatalog {
    #[serde(
        rename = "baseUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_url: Option<Option<String>>,
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
    #[serde(rename = "hasApiKey")]
    pub has_api_key: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "models")]
    pub models: Vec<models::LlmCatalogModel>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "requiresApiKey")]
    pub requires_api_key: bool,
    #[serde(rename = "requiresBaseUrl")]
    pub requires_base_url: bool,
    #[serde(rename = "status")]
    pub status: models::LlmProviderCatalogStatus,
}

impl LlmProviderCatalog {
    pub fn new(
        has_api_key: bool,
        id: String,
        models: Vec<models::LlmCatalogModel>,
        name: String,
        requires_api_key: bool,
        requires_base_url: bool,
        status: models::LlmProviderCatalogStatus,
    ) -> LlmProviderCatalog {
        LlmProviderCatalog {
            base_url: None,
            error: None,
            has_api_key,
            id,
            models,
            name,
            requires_api_key,
            requires_base_url,
            status,
        }
    }
}
