/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LlmCatalog {
    #[serde(rename = "localModels")]
    pub local_models: Vec<models::LlmCatalogModel>,
    #[serde(rename = "providers")]
    pub providers: Vec<models::LlmProviderCatalog>,
}

impl LlmCatalog {
    pub fn new(
        local_models: Vec<models::LlmCatalogModel>,
        providers: Vec<models::LlmProviderCatalog>,
    ) -> LlmCatalog {
        LlmCatalog {
            local_models,
            providers,
        }
    }
}
