/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LlmProviderCatalogStatus {
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "missing_configuration")]
    MissingConfiguration,
    #[serde(rename = "discovery_failed")]
    DiscoveryFailed,
}

impl std::fmt::Display for LlmProviderCatalogStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ready => write!(f, "ready"),
            Self::MissingConfiguration => write!(f, "missing_configuration"),
            Self::DiscoveryFailed => write!(f, "discovery_failed"),
        }
    }
}

impl Default for LlmProviderCatalogStatus {
    fn default() -> LlmProviderCatalogStatus {
        Self::Ready
    }
}
