/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LlmLoadRequest {
    #[serde(
        rename = "options",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub options: Option<Option<Box<models::LlmGenerationOptions>>>,
    #[serde(rename = "target")]
    pub target: Box<models::LlmTarget>,
}

impl LlmLoadRequest {
    pub fn new(target: models::LlmTarget) -> LlmLoadRequest {
        LlmLoadRequest {
            options: None,
            target: Box::new(target),
        }
    }
}
