/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LlmCatalogModel {
    #[serde(rename = "languages")]
    pub languages: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "target")]
    pub target: Box<models::LlmTarget>,
}

impl LlmCatalogModel {
    pub fn new(languages: Vec<String>, name: String, target: models::LlmTarget) -> LlmCatalogModel {
        LlmCatalogModel {
            languages,
            name,
            target: Box::new(target),
        }
    }
}
