/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LlmState {
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::LlmStateStatus,
    #[serde(
        rename = "target",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub target: Option<Option<Box<models::LlmTarget>>>,
}

impl LlmState {
    pub fn new(status: models::LlmStateStatus) -> LlmState {
        LlmState {
            error: None,
            status,
            target: None,
        }
    }
}
