/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LlmTargetKind {
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "provider")]
    Provider,
}

impl std::fmt::Display for LlmTargetKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Local => write!(f, "local"),
            Self::Provider => write!(f, "provider"),
        }
    }
}

impl Default for LlmTargetKind {
    fn default() -> LlmTargetKind {
        Self::Local
    }
}
