/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LlmTarget {
    #[serde(rename = "kind")]
    pub kind: models::LlmTargetKind,
    #[serde(rename = "modelId")]
    pub model_id: String,
    #[serde(
        rename = "providerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub provider_id: Option<Option<String>>,
}

impl LlmTarget {
    pub fn new(kind: models::LlmTargetKind, model_id: String) -> LlmTarget {
        LlmTarget {
            kind,
            model_id,
            provider_id: None,
        }
    }
}
