/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaskDataPatch {
    /// Hex-encoded blake3 hash of an immutable blob.
    #[serde(
        rename = "blob",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blob: Option<Option<String>>,
}

impl MaskDataPatch {
    pub fn new() -> MaskDataPatch {
        MaskDataPatch { blob: None }
    }
}
