/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MaskRole {
    #[serde(rename = "brushInpaint")]
    BrushInpaint,
    #[serde(rename = "segment")]
    Segment,
}

impl std::fmt::Display for MaskRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BrushInpaint => write!(f, "brushInpaint"),
            Self::Segment => write!(f, "segment"),
        }
    }
}

impl Default for MaskRole {
    fn default() -> MaskRole {
        Self::BrushInpaint
    }
}
