/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetaInfo {
    #[serde(rename = "mlDevice")]
    pub ml_device: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl MetaInfo {
    pub fn new(ml_device: String, version: String) -> MetaInfo {
        MetaInfo { ml_device, version }
    }
}
