/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModelLocationMode {
    #[serde(rename = "use_existing")]
    UseExisting,
    #[serde(rename = "move_existing")]
    MoveExisting,
}

impl std::fmt::Display for ModelLocationMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UseExisting => write!(f, "use_existing"),
            Self::MoveExisting => write!(f, "move_existing"),
        }
    }
}

impl Default for ModelLocationMode {
    fn default() -> ModelLocationMode {
        Self::UseExisting
    }
}
