/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeKindOneOf {
    #[serde(rename = "image")]
    pub image: Box<models::ImageData>,
}

impl NodeKindOneOf {
    pub fn new(image: models::ImageData) -> NodeKindOneOf {
        NodeKindOneOf {
            image: Box::new(image),
        }
    }
}
