/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeKindOneOf1 {
    #[serde(rename = "text")]
    pub text: Box<models::TextData>,
}

impl NodeKindOneOf1 {
    pub fn new(text: models::TextData) -> NodeKindOneOf1 {
        NodeKindOneOf1 {
            text: Box::new(text),
        }
    }
}
