/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeKindOneOf2 {
    #[serde(rename = "mask")]
    pub mask: Box<models::MaskData>,
}

impl NodeKindOneOf2 {
    pub fn new(mask: models::MaskData) -> NodeKindOneOf2 {
        NodeKindOneOf2 {
            mask: Box::new(mask),
        }
    }
}
