/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeDataPatchOneOf {
    #[serde(rename = "text")]
    pub text: Box<models::TextDataPatch>,
}

impl NodeDataPatchOneOf {
    pub fn new(text: models::TextDataPatch) -> NodeDataPatchOneOf {
        NodeDataPatchOneOf {
            text: Box::new(text),
        }
    }
}
