/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodeDataPatch {
    NodeDataPatchOneOf(Box<models::NodeDataPatchOneOf>),
    NodeDataPatchOneOf1(Box<models::NodeDataPatchOneOf1>),
    NodeDataPatchOneOf2(Box<models::NodeDataPatchOneOf2>),
}

impl Default for NodeDataPatch {
    fn default() -> Self {
        Self::NodeDataPatchOneOf(Default::default())
    }
}
