/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodePatch {
    #[serde(
        rename = "data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub data: Option<Option<Box<models::NodeDataPatch>>>,
    #[serde(
        rename = "transform",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub transform: Option<Option<Box<models::Transform>>>,
    #[serde(
        rename = "visible",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub visible: Option<Option<bool>>,
}

impl NodePatch {
    pub fn new() -> NodePatch {
        NodePatch {
            data: None,
            transform: None,
            visible: None,
        }
    }
}
