/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "kind")]
    pub kind: Box<models::NodeKind>,
    #[serde(rename = "transform", skip_serializing_if = "Option::is_none")]
    pub transform: Option<Box<models::Transform>>,
    #[serde(rename = "visible")]
    pub visible: bool,
}

impl Node {
    pub fn new(id: uuid::Uuid, kind: models::NodeKind, visible: bool) -> Node {
        Node {
            id,
            kind: Box::new(kind),
            transform: None,
            visible,
        }
    }
}
