/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeDataPatchOneOf1 {
    #[serde(rename = "image")]
    pub image: Box<models::ImageDataPatch>,
}

impl NodeDataPatchOneOf1 {
    pub fn new(image: models::ImageDataPatch) -> NodeDataPatchOneOf1 {
        NodeDataPatchOneOf1 {
            image: Box::new(image),
        }
    }
}
