/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodeKind {
    NodeKindOneOf(Box<models::NodeKindOneOf>),
    NodeKindOneOf1(Box<models::NodeKindOneOf1>),
    NodeKindOneOf2(Box<models::NodeKindOneOf2>),
}

impl Default for NodeKind {
    fn default() -> Self {
        Self::NodeKindOneOf(Default::default())
    }
}
