/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Op {
    OpOneOf(Box<models::OpOneOf>),
    OpOneOf1(Box<models::OpOneOf1>),
    OpOneOf2(Box<models::OpOneOf2>),
    OpOneOf3(Box<models::OpOneOf3>),
    OpOneOf4(Box<models::OpOneOf4>),
    OpOneOf5(Box<models::OpOneOf5>),
    OpOneOf6(Box<models::OpOneOf6>),
    OpOneOf7(Box<models::OpOneOf7>),
    OpOneOf8(Box<models::OpOneOf8>),
    OpOneOf9(Box<models::OpOneOf9>),
}

impl Default for Op {
    fn default() -> Self {
        Self::OpOneOf(Default::default())
    }
}
