/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf5AddNode {
    #[serde(rename = "at")]
    pub at: u32,
    #[serde(rename = "node")]
    pub node: Box<models::Node>,
    #[serde(rename = "page")]
    pub page: uuid::Uuid,
}

impl OpOneOf5AddNode {
    pub fn new(at: u32, node: models::Node, page: uuid::Uuid) -> OpOneOf5AddNode {
        OpOneOf5AddNode {
            at,
            node: Box::new(node),
            page,
        }
    }
}
