/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf3UpdatePage {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "patch")]
    pub patch: Box<models::PagePatch>,
    #[serde(rename = "prev", skip_serializing_if = "Option::is_none")]
    pub prev: Option<Box<models::PagePatch>>,
}

impl OpOneOf3UpdatePage {
    pub fn new(id: uuid::Uuid, patch: models::PagePatch) -> OpOneOf3UpdatePage {
        OpOneOf3UpdatePage {
            id,
            patch: Box::new(patch),
            prev: None,
        }
    }
}
