/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf3 {
    #[serde(rename = "updatePage")]
    pub update_page: Box<models::OpOneOf3UpdatePage>,
}

impl OpOneOf3 {
    pub fn new(update_page: models::OpOneOf3UpdatePage) -> OpOneOf3 {
        OpOneOf3 {
            update_page: Box::new(update_page),
        }
    }
}
