/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf7UpdateNode {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "page")]
    pub page: uuid::Uuid,
    #[serde(rename = "patch")]
    pub patch: Box<models::NodePatch>,
    #[serde(rename = "prev", skip_serializing_if = "Option::is_none")]
    pub prev: Option<Box<models::NodePatch>>,
}

impl OpOneOf7UpdateNode {
    pub fn new(id: uuid::Uuid, page: uuid::Uuid, patch: models::NodePatch) -> OpOneOf7UpdateNode {
        OpOneOf7UpdateNode {
            id,
            page,
            patch: Box::new(patch),
            prev: None,
        }
    }
}
