/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf7 {
    #[serde(rename = "updateNode")]
    pub update_node: Box<models::OpOneOf7UpdateNode>,
}

impl OpOneOf7 {
    pub fn new(update_node: models::OpOneOf7UpdateNode) -> OpOneOf7 {
        OpOneOf7 {
            update_node: Box::new(update_node),
        }
    }
}
