/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf4 {
    #[serde(rename = "reorderPages")]
    pub reorder_pages: Box<models::OpOneOf4ReorderPages>,
}

impl OpOneOf4 {
    pub fn new(reorder_pages: models::OpOneOf4ReorderPages) -> OpOneOf4 {
        OpOneOf4 {
            reorder_pages: Box::new(reorder_pages),
        }
    }
}
