/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf {
    #[serde(rename = "updateProjectMeta")]
    pub update_project_meta: Box<models::OpOneOfUpdateProjectMeta>,
}

impl OpOneOf {
    pub fn new(update_project_meta: models::OpOneOfUpdateProjectMeta) -> OpOneOf {
        OpOneOf {
            update_project_meta: Box::new(update_project_meta),
        }
    }
}
