/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf9 {
    #[serde(rename = "batch")]
    pub batch: Box<models::OpOneOf9Batch>,
}

impl OpOneOf9 {
    pub fn new(batch: models::OpOneOf9Batch) -> OpOneOf9 {
        OpOneOf9 {
            batch: Box::new(batch),
        }
    }
}
