/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf2 {
    #[serde(rename = "removePage")]
    pub remove_page: Box<models::OpOneOf2RemovePage>,
}

impl OpOneOf2 {
    pub fn new(remove_page: models::OpOneOf2RemovePage) -> OpOneOf2 {
        OpOneOf2 {
            remove_page: Box::new(remove_page),
        }
    }
}
