/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf2RemovePage {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "prev_index")]
    pub prev_index: u32,
    #[serde(rename = "prev_page")]
    pub prev_page: Box<models::Page>,
}

impl OpOneOf2RemovePage {
    pub fn new(id: uuid::Uuid, prev_index: u32, prev_page: models::Page) -> OpOneOf2RemovePage {
        OpOneOf2RemovePage {
            id,
            prev_index,
            prev_page: Box::new(prev_page),
        }
    }
}
