/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf1AddPage {
    #[serde(rename = "at")]
    pub at: u32,
    #[serde(rename = "page")]
    pub page: Box<models::Page>,
}

impl OpOneOf1AddPage {
    pub fn new(at: u32, page: models::Page) -> OpOneOf1AddPage {
        OpOneOf1AddPage {
            at,
            page: Box::new(page),
        }
    }
}
