/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf8ReorderNodes {
    #[serde(rename = "order")]
    pub order: Vec<uuid::Uuid>,
    #[serde(rename = "page")]
    pub page: uuid::Uuid,
    #[serde(rename = "prev_order")]
    pub prev_order: Vec<uuid::Uuid>,
}

impl OpOneOf8ReorderNodes {
    pub fn new(
        order: Vec<uuid::Uuid>,
        page: uuid::Uuid,
        prev_order: Vec<uuid::Uuid>,
    ) -> OpOneOf8ReorderNodes {
        OpOneOf8ReorderNodes {
            order,
            page,
            prev_order,
        }
    }
}
