/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf1 {
    #[serde(rename = "addPage")]
    pub add_page: Box<models::OpOneOf1AddPage>,
}

impl OpOneOf1 {
    pub fn new(add_page: models::OpOneOf1AddPage) -> OpOneOf1 {
        OpOneOf1 {
            add_page: Box::new(add_page),
        }
    }
}
