/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf5 {
    #[serde(rename = "addNode")]
    pub add_node: Box<models::OpOneOf5AddNode>,
}

impl OpOneOf5 {
    pub fn new(add_node: models::OpOneOf5AddNode) -> OpOneOf5 {
        OpOneOf5 {
            add_node: Box::new(add_node),
        }
    }
}
