/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf4ReorderPages {
    #[serde(rename = "order")]
    pub order: Vec<uuid::Uuid>,
    #[serde(rename = "prev_order")]
    pub prev_order: Vec<uuid::Uuid>,
}

impl OpOneOf4ReorderPages {
    pub fn new(order: Vec<uuid::Uuid>, prev_order: Vec<uuid::Uuid>) -> OpOneOf4ReorderPages {
        OpOneOf4ReorderPages { order, prev_order }
    }
}
