/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf8 {
    #[serde(rename = "reorderNodes")]
    pub reorder_nodes: Box<models::OpOneOf8ReorderNodes>,
}

impl OpOneOf8 {
    pub fn new(reorder_nodes: models::OpOneOf8ReorderNodes) -> OpOneOf8 {
        OpOneOf8 {
            reorder_nodes: Box::new(reorder_nodes),
        }
    }
}
