/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf6RemoveNode {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "page")]
    pub page: uuid::Uuid,
    #[serde(rename = "prev_index")]
    pub prev_index: u32,
    #[serde(rename = "prev_node")]
    pub prev_node: Box<models::Node>,
}

impl OpOneOf6RemoveNode {
    pub fn new(
        id: uuid::Uuid,
        page: uuid::Uuid,
        prev_index: u32,
        prev_node: models::Node,
    ) -> OpOneOf6RemoveNode {
        OpOneOf6RemoveNode {
            id,
            page,
            prev_index,
            prev_node: Box::new(prev_node),
        }
    }
}
