/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOfUpdateProjectMeta {
    #[serde(rename = "patch")]
    pub patch: Box<models::ProjectMetaPatch>,
    #[serde(rename = "prev", skip_serializing_if = "Option::is_none")]
    pub prev: Option<Box<models::ProjectMetaPatch>>,
}

impl OpOneOfUpdateProjectMeta {
    pub fn new(patch: models::ProjectMetaPatch) -> OpOneOfUpdateProjectMeta {
        OpOneOfUpdateProjectMeta {
            patch: Box::new(patch),
            prev: None,
        }
    }
}
