/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf9Batch {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "ops")]
    pub ops: Vec<models::Op>,
}

impl OpOneOf9Batch {
    pub fn new(label: String, ops: Vec<models::Op>) -> OpOneOf9Batch {
        OpOneOf9Batch { label, ops }
    }
}
