/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpOneOf6 {
    #[serde(rename = "removeNode")]
    pub remove_node: Box<models::OpOneOf6RemoveNode>,
}

impl OpOneOf6 {
    pub fn new(remove_node: models::OpOneOf6RemoveNode) -> OpOneOf6 {
        OpOneOf6 {
            remove_node: Box::new(remove_node),
        }
    }
}
