/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenProjectRequest {
    /// `.khrproj/` directory basename (no extension). Must exist under the managed projects directory.
    #[serde(rename = "id")]
    pub id: String,
}

impl OpenProjectRequest {
    pub fn new(id: String) -> OpenProjectRequest {
        OpenProjectRequest { id }
    }
}
