/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineStatusOneOf {
    #[serde(rename = "status")]
    pub status: Status,
}

impl PipelineStatusOneOf {
    pub fn new(status: Status) -> PipelineStatusOneOf {
        PipelineStatusOneOf { status }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "running")]
    Running,
}

impl Default for Status {
    fn default() -> Status {
        Self::Running
    }
}
