/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PipelineStep {
    #[serde(rename = "detect")]
    Detect,
    #[serde(rename = "ocr")]
    Ocr,
    #[serde(rename = "inpaint")]
    Inpaint,
    #[serde(rename = "llmGenerate")]
    LlmGenerate,
    #[serde(rename = "render")]
    Render,
}

impl std::fmt::Display for PipelineStep {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Detect => write!(f, "detect"),
            Self::Ocr => write!(f, "ocr"),
            Self::Inpaint => write!(f, "inpaint"),
            Self::LlmGenerate => write!(f, "llmGenerate"),
            Self::Render => write!(f, "render"),
        }
    }
}

impl Default for PipelineStep {
    fn default() -> PipelineStep {
        Self::Detect
    }
}
