/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineProgress {
    #[serde(rename = "currentPage")]
    pub current_page: u32,
    #[serde(rename = "currentStepIndex")]
    pub current_step_index: u32,
    #[serde(rename = "jobId")]
    pub job_id: String,
    #[serde(rename = "overallPercent")]
    pub overall_percent: u32,
    #[serde(rename = "status")]
    pub status: Box<models::PipelineStatus>,
    #[serde(
        rename = "step",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub step: Option<Option<models::PipelineStep>>,
    #[serde(rename = "totalPages")]
    pub total_pages: u32,
    #[serde(rename = "totalSteps")]
    pub total_steps: u32,
}

impl PipelineProgress {
    pub fn new(
        current_page: u32,
        current_step_index: u32,
        job_id: String,
        overall_percent: u32,
        status: models::PipelineStatus,
        total_pages: u32,
        total_steps: u32,
    ) -> PipelineProgress {
        PipelineProgress {
            current_page,
            current_step_index,
            job_id,
            overall_percent,
            status: Box::new(status),
            step: None,
            total_pages,
            total_steps,
        }
    }
}
