/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PipelineConfig : Engine selection for each pipeline stage. Values are engine IDs (e.g. \"pp-doclayout-v3\", \"comic-text-detector\"). Empty string means use default.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineConfig {
    #[serde(rename = "detector", skip_serializing_if = "Option::is_none")]
    pub detector: Option<String>,
    #[serde(rename = "font_detector", skip_serializing_if = "Option::is_none")]
    pub font_detector: Option<String>,
    #[serde(rename = "inpainter", skip_serializing_if = "Option::is_none")]
    pub inpainter: Option<String>,
    #[serde(rename = "ocr", skip_serializing_if = "Option::is_none")]
    pub ocr: Option<String>,
    #[serde(rename = "renderer", skip_serializing_if = "Option::is_none")]
    pub renderer: Option<String>,
    #[serde(rename = "segmenter", skip_serializing_if = "Option::is_none")]
    pub segmenter: Option<String>,
    #[serde(rename = "translator", skip_serializing_if = "Option::is_none")]
    pub translator: Option<String>,
}

impl PipelineConfig {
    /// Engine selection for each pipeline stage. Values are engine IDs (e.g. \"pp-doclayout-v3\", \"comic-text-detector\"). Empty string means use default.
    pub fn new() -> PipelineConfig {
        PipelineConfig {
            detector: None,
            font_detector: None,
            inpainter: None,
            ocr: None,
            renderer: None,
            segmenter: None,
            translator: None,
        }
    }
}
