/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineConfigPatch {
    #[serde(
        rename = "detector",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub detector: Option<Option<String>>,
    #[serde(
        rename = "fontDetector",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub font_detector: Option<Option<String>>,
    #[serde(
        rename = "inpainter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inpainter: Option<Option<String>>,
    #[serde(
        rename = "ocr",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ocr: Option<Option<String>>,
    #[serde(
        rename = "renderer",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub renderer: Option<Option<String>>,
    #[serde(
        rename = "segmenter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub segmenter: Option<Option<String>>,
    #[serde(
        rename = "translator",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub translator: Option<Option<String>>,
}

impl PipelineConfigPatch {
    pub fn new() -> PipelineConfigPatch {
        PipelineConfigPatch {
            detector: None,
            font_detector: None,
            inpainter: None,
            ocr: None,
            renderer: None,
            segmenter: None,
            translator: None,
        }
    }
}
