/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMeta {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<Box<models::ProjectStyle>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl ProjectMeta {
    pub fn new(created_at: String, name: String, updated_at: String) -> ProjectMeta {
        ProjectMeta {
            created_at,
            name,
            style: None,
            updated_at,
        }
    }
}
