/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectSummary {
    /// Stable identifier — the `.khrproj` directory basename (without the extension). Clients address projects by this.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Absolute filesystem path. Informational; clients never need to pass it back in — they use `id`.
    #[serde(rename = "path")]
    pub path: String,
    /// Last modification time of the project directory on disk (ms since UNIX epoch). Used for \"recent projects\" ordering.
    #[serde(rename = "updatedAtMs", skip_serializing_if = "Option::is_none")]
    pub updated_at_ms: Option<u64>,
}

impl ProjectSummary {
    pub fn new(id: String, name: String, path: String) -> ProjectSummary {
        ProjectSummary {
            id,
            name,
            path,
            updated_at_ms: None,
        }
    }
}
