/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderConfig {
    /// Populated from the keyring on `load()`, never written to config.toml. Serializes as `\"[REDACTED]\"` in API responses. Populated from keyring on `load()`. Serializes as `\"[REDACTED]\"`.
    #[serde(
        rename = "api_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_key: Option<Option<String>>,
    #[serde(
        rename = "base_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_url: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
}

impl ProviderConfig {
    pub fn new(id: String) -> ProviderConfig {
        ProviderConfig {
            api_key: None,
            base_url: None,
            id,
        }
    }
}
