/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderSecretRequest {
    #[serde(rename = "secret")]
    pub secret: String,
}

impl ProviderSecretRequest {
    pub fn new(secret: String) -> ProviderSecretRequest {
        ProviderSecretRequest { secret }
    }
}
