/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderPatch {
    /// `\"[REDACTED]\"` → keep existing keyring secret; empty → clear; otherwise save.
    #[serde(
        rename = "apiKey",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_key: Option<Option<String>>,
    #[serde(
        rename = "baseUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_url: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
}

impl ProviderPatch {
    pub fn new(id: String) -> ProviderPatch {
        ProviderPatch {
            api_key: None,
            base_url: None,
            id,
        }
    }
}
