/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutMaskResponse {
    /// Hex-encoded blake3 hash of an immutable blob.
    #[serde(rename = "blob")]
    pub blob: String,
    #[serde(rename = "node")]
    pub node: uuid::Uuid,
}

impl PutMaskResponse {
    pub fn new(blob: String, node: uuid::Uuid) -> PutMaskResponse {
        PutMaskResponse { blob, node }
    }
}
