/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReadingOrder {
    #[serde(rename = "rtl")]
    Rtl,
    #[serde(rename = "ltr")]
    Ltr,
    #[serde(rename = "custom")]
    Custom,
}

impl std::fmt::Display for ReadingOrder {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Rtl => write!(f, "rtl"),
            Self::Ltr => write!(f, "ltr"),
            Self::Custom => write!(f, "custom"),
        }
    }
}

impl Default for ReadingOrder {
    fn default() -> ReadingOrder {
        Self::Rtl
    }
}
