/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RedownloadModelResponse {
    #[serde(rename = "operationId")]
    pub operation_id: String,
    #[serde(rename = "removedBytes")]
    pub removed_bytes: u64,
}

impl RedownloadModelResponse {
    pub fn new(operation_id: String, removed_bytes: u64) -> RedownloadModelResponse {
        RedownloadModelResponse {
            operation_id,
            removed_bytes,
        }
    }
}
