/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Region {
    #[serde(rename = "height")]
    pub height: u32,
    #[serde(rename = "width")]
    pub width: u32,
    #[serde(rename = "x")]
    pub x: u32,
    #[serde(rename = "y")]
    pub y: u32,
}

impl Region {
    pub fn new(height: u32, width: u32, x: u32, y: u32) -> Region {
        Region {
            height,
            width,
            x,
            y,
        }
    }
}
