/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SceneSnapshot : JSON-shaped scene snapshot for the UI (no postcard decoder in JS).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SceneSnapshot {
    #[serde(rename = "epoch")]
    pub epoch: u64,
    #[serde(rename = "scene")]
    pub scene: Box<models::Scene>,
}

impl SceneSnapshot {
    /// JSON-shaped scene snapshot for the UI (no postcard decoder in JS).
    pub fn new(epoch: u64, scene: models::Scene) -> SceneSnapshot {
        SceneSnapshot {
            epoch,
            scene: Box::new(scene),
        }
    }
}
