/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Scene {
    /// Pages in insertion order; `IndexMap` ordering *is* the page order.
    #[serde(rename = "pages")]
    pub pages: std::collections::HashMap<String, models::Page>,
    #[serde(rename = "project")]
    pub project: Box<models::ProjectMeta>,
}

impl Scene {
    pub fn new(
        pages: std::collections::HashMap<String, models::Page>,
        project: models::ProjectMeta,
    ) -> Scene {
        Scene {
            pages,
            project: Box::new(project),
        }
    }
}
