/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetModelLocationRequest {
    #[serde(rename = "mode")]
    pub mode: models::ModelLocationMode,
    #[serde(rename = "path")]
    pub path: String,
}

impl SetModelLocationRequest {
    pub fn new(mode: models::ModelLocationMode, path: String) -> SetModelLocationRequest {
        SetModelLocationRequest { mode, path }
    }
}
