/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetModelLocationResponse {
    #[serde(rename = "copiedBytes")]
    pub copied_bytes: u64,
    #[serde(rename = "modelsPath")]
    pub models_path: String,
    #[serde(rename = "restartRequired")]
    pub restart_required: bool,
    #[serde(rename = "sourceRemoved")]
    pub source_removed: bool,
}

impl SetModelLocationResponse {
    pub fn new(
        copied_bytes: u64,
        models_path: String,
        restart_required: bool,
        source_removed: bool,
    ) -> SetModelLocationResponse {
        SetModelLocationResponse {
            copied_bytes,
            models_path,
            restart_required,
            source_removed,
        }
    }
}
