/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotEvent {
    #[serde(rename = "downloads")]
    pub downloads: Vec<models::DownloadProgress>,
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::JobSummary>,
}

impl SnapshotEvent {
    pub fn new(
        downloads: Vec<models::DownloadProgress>,
        jobs: Vec<models::JobSummary>,
    ) -> SnapshotEvent {
        SnapshotEvent { downloads, jobs }
    }
}
