/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartDownloadRequest {
    /// Package id, as declared via `declare_hf_model_package!` (e.g. `\"model:comic-text-detector:yolo-v5\"`).
    #[serde(rename = "modelId")]
    pub model_id: String,
}

impl StartDownloadRequest {
    pub fn new(model_id: String) -> StartDownloadRequest {
        StartDownloadRequest { model_id }
    }
}
