/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartDownloadResponse {
    /// Operation id. Reusing the package id keeps ids meaningful for clients watching progress events.
    #[serde(rename = "operationId")]
    pub operation_id: String,
}

impl StartDownloadResponse {
    pub fn new(operation_id: String) -> StartDownloadResponse {
        StartDownloadResponse { operation_id }
    }
}
