/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartPipelineResponse {
    #[serde(rename = "operationId")]
    pub operation_id: String,
}

impl StartPipelineResponse {
    pub fn new(operation_id: String) -> StartPipelineResponse {
        StartPipelineResponse { operation_id }
    }
}
