/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartPipelineRequest {
    /// Internal correlation used by the UI's debounced auto-render. When set, the request must be a single-page, renderer-only pipeline.
    #[serde(
        rename = "autoRenderEpoch",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_render_epoch: Option<Option<u64>>,
    #[serde(
        rename = "defaultFont",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_font: Option<Option<String>>,
    /// `None` → whole project, `Some(pages)` → just those pages.
    #[serde(
        rename = "pages",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pages: Option<Option<Vec<uuid::Uuid>>>,
    #[serde(
        rename = "readingOrder",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reading_order: Option<Option<models::ReadingOrder>>,
    /// Optional bounding-box hint for inpainter engines (repair-brush).
    #[serde(
        rename = "region",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub region: Option<Option<Box<models::Region>>>,
    /// Engine ids (`inventory::submit!` ids) to run in order.
    #[serde(rename = "steps")]
    pub steps: Vec<String>,
    #[serde(
        rename = "systemPrompt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub system_prompt: Option<Option<String>>,
    #[serde(
        rename = "targetLanguage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub target_language: Option<Option<String>>,
    /// Optional text-node ids for engines that can operate on individual blocks.
    #[serde(
        rename = "textNodeIds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub text_node_ids: Option<Option<Vec<uuid::Uuid>>>,
}

impl StartPipelineRequest {
    pub fn new(steps: Vec<String>) -> StartPipelineRequest {
        StartPipelineRequest {
            auto_render_epoch: None,
            default_font: None,
            pages: None,
            reading_order: None,
            region: None,
            steps,
            system_prompt: None,
            target_language: None,
            text_node_ids: None,
        }
    }
}
