/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageCleanupResponse {
    #[serde(rename = "removedBytes")]
    pub removed_bytes: u64,
}

impl StorageCleanupResponse {
    pub fn new(removed_bytes: u64) -> StorageCleanupResponse {
        StorageCleanupResponse { removed_bytes }
    }
}
