/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageSummary {
    #[serde(rename = "customModelsPath")]
    pub custom_models_path: bool,
    #[serde(rename = "dataPath")]
    pub data_path: String,
    #[serde(rename = "downloadedLocalModels")]
    pub downloaded_local_models: u32,
    #[serde(rename = "modelsBytes")]
    pub models_bytes: u64,
    #[serde(rename = "modelsPath")]
    pub models_path: String,
    #[serde(rename = "temporaryBytes")]
    pub temporary_bytes: u64,
}

impl StorageSummary {
    pub fn new(
        custom_models_path: bool,
        data_path: String,
        downloaded_local_models: u32,
        models_bytes: u64,
        models_path: String,
        temporary_bytes: u64,
    ) -> StorageSummary {
        StorageSummary {
            custom_models_path,
            data_path,
            downloaded_local_models,
            models_bytes,
            models_path,
            temporary_bytes,
        }
    }
}
