/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextData {
    #[serde(rename = "confidence", skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f32>,
    #[serde(
        rename = "detectedFontSizePx",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub detected_font_size_px: Option<Option<f32>>,
    #[serde(
        rename = "detector",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub detector: Option<Option<String>>,
    #[serde(
        rename = "fontPrediction",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub font_prediction: Option<Option<Box<models::FontPrediction>>>,
    #[serde(
        rename = "linePolygons",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub line_polygons: Option<Option<Vec<Vec<Vec<f32>>>>>,
    #[serde(rename = "lockLayoutBox", skip_serializing_if = "Option::is_none")]
    pub lock_layout_box: Option<bool>,
    #[serde(
        rename = "renderedDirection",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rendered_direction: Option<Option<models::TextDirection>>,
    #[serde(
        rename = "rotationDeg",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rotation_deg: Option<Option<f32>>,
    #[serde(
        rename = "sourceDirection",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_direction: Option<Option<models::TextDirection>>,
    #[serde(
        rename = "sourceLang",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_lang: Option<Option<String>>,
    /// Renderer-produced sprite for this block.
    #[serde(
        rename = "sprite",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sprite: Option<Option<String>>,
    /// Sprite placement when the renderer expands past the bubble geometry.
    #[serde(
        rename = "spriteTransform",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sprite_transform: Option<Option<Box<models::Transform>>>,
    #[serde(
        rename = "style",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub style: Option<Option<Box<models::TextStyle>>>,
    #[serde(
        rename = "text",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub text: Option<Option<String>>,
    #[serde(
        rename = "translation",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub translation: Option<Option<String>>,
}

impl TextData {
    pub fn new() -> TextData {
        TextData {
            confidence: None,
            detected_font_size_px: None,
            detector: None,
            font_prediction: None,
            line_polygons: None,
            lock_layout_box: None,
            rendered_direction: None,
            rotation_deg: None,
            source_direction: None,
            source_lang: None,
            sprite: None,
            sprite_transform: None,
            style: None,
            text: None,
            translation: None,
        }
    }
}
