/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextStrokeStyle {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<Vec<u32>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(
        rename = "widthPx",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub width_px: Option<Option<f32>>,
}

impl TextStrokeStyle {
    pub fn new() -> TextStrokeStyle {
        TextStrokeStyle {
            color: None,
            enabled: None,
            width_px: None,
        }
    }
}
