/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextStyle {
    #[serde(rename = "color")]
    pub color: Vec<u32>,
    #[serde(
        rename = "effect",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub effect: Option<Option<Box<models::TextShaderEffect>>>,
    #[serde(rename = "fontFamilies")]
    pub font_families: Vec<String>,
    #[serde(
        rename = "fontSize",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub font_size: Option<Option<f32>>,
    #[serde(
        rename = "stroke",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stroke: Option<Option<Box<models::TextStrokeStyle>>>,
    #[serde(
        rename = "textAlign",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub text_align: Option<Option<models::TextAlign>>,
}

impl TextStyle {
    pub fn new(color: Vec<u32>, font_families: Vec<String>) -> TextStyle {
        TextStyle {
            color,
            effect: None,
            font_families,
            font_size: None,
            stroke: None,
            text_align: None,
        }
    }
}
