/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopFont {
    #[serde(rename = "index")]
    pub index: u32,
    #[serde(rename = "score")]
    pub score: f32,
}

impl TopFont {
    pub fn new(index: u32, score: f32) -> TopFont {
        TopFont { index, score }
    }
}
