/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transform {
    #[serde(rename = "height")]
    pub height: f32,
    #[serde(rename = "rotationDeg", skip_serializing_if = "Option::is_none")]
    pub rotation_deg: Option<f32>,
    #[serde(rename = "width")]
    pub width: f32,
    #[serde(rename = "x")]
    pub x: f32,
    #[serde(rename = "y")]
    pub y: f32,
}

impl Transform {
    pub fn new(height: f32, width: f32, x: f32, y: f32) -> Transform {
        Transform {
            height,
            rotation_deg: None,
            width,
            x,
            y,
        }
    }
}
