// Auto-generated by openapi-generator — silence clippy across the whole
// crate so CI stays green without hand-patching generator output.
#![allow(unused_imports)]
#![allow(clippy::all)]
#![allow(clippy::pedantic)]

extern crate reqwest;
extern crate serde;
extern crate serde_json;
extern crate serde_repr;
extern crate url;

pub mod apis;
pub mod models;
