[env]
# refer: https://stackoverflow.com/questions/43577885/is-there-a-cargo-environment-variable-for-the-workspace-directory
CARGO_WORKSPACE_DIR = { value = "", relative = true }
# llama.cpp release tag
LLAMA_CPP_TAG = "b8935"
# CUDA 13.0 requires C++17
NVCC_PREPEND_FLAGS = "-std=c++17"
# override nvidia-smi compute capability
CUDA_COMPUTE_CAP = "80"
