/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DataConfig } from './dataConfig'
import type { HttpConfig } from './httpConfig'
import type { PipelineConfig } from './pipelineConfig'
import type { ProviderConfig } from './providerConfig'

export interface AppConfig {
  data?: DataConfig
  http?: HttpConfig
  pipeline?: PipelineConfig
  providers?: ProviderConfig[]
}
