/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { CodexAuthAttemptStatus } from './codexAuthAttemptStatus'

export interface CodexDeviceLoginStatus {
  /** @nullable */
  accountId?: string | null
  /** @nullable */
  error?: string | null
  loginId: string
  status: CodexAuthAttemptStatus
}
