/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { PageId } from './pageId'

export interface CodexImageGenerationOptions {
  /** @nullable */
  instructions?: string | null
  /** @nullable */
  model?: string | null
  pageId: PageId
  prompt: string
  /** @nullable */
  quality?: string | null
  /** @nullable */
  size?: string | null
}
