/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type CodexAuthAttemptStatus =
  (typeof CodexAuthAttemptStatus)[keyof typeof CodexAuthAttemptStatus]

export const CodexAuthAttemptStatus = {
  pending: 'pending',
  succeeded: 'succeeded',
  failed: 'failed',
} as const
