/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface CodexDeviceLogin {
  /** @minimum 0 */
  intervalSeconds: number
  loginId: string
  /** @minimum 0 */
  timeoutSeconds: number
  userCode: string
  verificationUrl: string
}
