/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type CodexAuthAttemptStatus =
  (typeof CodexAuthAttemptStatus)[keyof typeof CodexAuthAttemptStatus]

export const CodexAuthAttemptStatus = {
  pending: 'pending',
  succeeded: 'succeeded',
  failed: 'failed',
} as const
