/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { BinaryPayload } from './binaryPayload'

export type CreatePagesBody = {
  /** Image files to import as pages, in upload order. */
  file: BinaryPayload[]
  /**
   * Whether existing pages should be removed before importing.
   * @nullable
   */
  replace?: boolean | null
}
