/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface DataConfig {
  /**
   * Optional model-library override. `None` uses `{path}/models`.
   * @nullable
   */
  models_path?: string | null
  path: string
}
