/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DownloadStatus } from './downloadStatus'

export interface DownloadProgress {
  /** @minimum 0 */
  downloaded: number
  filename: string
  id: string
  status: DownloadStatus
  /**
   * @minimum 0
   * @nullable
   */
  total?: number | null
}
