/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type DownloadStatus =
  | {
      status: 'started'
    }
  | {
      status: 'downloading'
    }
  | {
      status: 'completed'
    }
  | {
      reason: string
      status: 'failed'
    }
