/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { EngineCatalogEntry } from './engineCatalogEntry'

export interface EngineCatalog {
  bubbleSegmenters: EngineCatalogEntry[]
  detectors: EngineCatalogEntry[]
  fontDetectors: EngineCatalogEntry[]
  inpainters: EngineCatalogEntry[]
  ocr: EngineCatalogEntry[]
  renderers: EngineCatalogEntry[]
  segmenters: EngineCatalogEntry[]
  translators: EngineCatalogEntry[]
}
