/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ExportFormat = (typeof ExportFormat)[keyof typeof ExportFormat]

export const ExportFormat = {
  khr: 'khr',
  psd: 'psd',
  rendered: 'rendered',
  inpainted: 'inpainted',
} as const
