/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type FontSource = (typeof FontSource)[keyof typeof FontSource]

export const FontSource = {
  system: 'system',
  google: 'google',
} as const
