/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { GoogleFontVariant } from './googleFontVariant'

export interface GoogleFontEntry {
  category: string
  family: string
  subsets: string[]
  variants: GoogleFontVariant[]
}
