/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface HistoryResult {
  /**
   * New epoch. `None` only for a no-op undo/redo at the stack boundary.
   * @minimum 0
   * @nullable
   */
  epoch?: number | null
}
