/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface HttpConfigPatch {
  /**
   * @minimum 0
   * @nullable
   */
  connectTimeout?: number | null
  /**
   * @minimum 0
   * @nullable
   */
  maxRetries?: number | null
  /**
   * @minimum 0
   * @nullable
   */
  readTimeout?: number | null
}
