/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface HttpConfig {
  /** @minimum 0 */
  connect_timeout?: number
  /** @minimum 0 */
  max_retries?: number
  /** @minimum 0 */
  read_timeout?: number
}
