/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ImageRole = (typeof ImageRole)[keyof typeof ImageRole]

export const ImageRole = {
  source: 'source',
  inpainted: 'inpainted',
  rendered: 'rendered',
  custom: 'custom',
} as const
