/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ImportProjectParams = {
  /**
 * Optional absolute destination path for the extracted `.khrproj/`
directory. When omitted, the server allocates a directory under
`{data.path}/projects/` using a timestamp-and-random suffix. Must not
already exist when provided.
 * @nullable
 */
  path?: string | null
}
