/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus]

export const JobStatus = {
  running: 'running',
  completed: 'completed',
  completed_with_errors: 'completed_with_errors',
  cancelled: 'cancelled',
  failed: 'failed',
} as const
