/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DownloadProgress } from './downloadProgress'

export interface ListDownloadsResponse {
  downloads: DownloadProgress[]
}
