/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { LlmTarget } from './llmTarget'

export interface LlmCatalogModel {
  languages: string[]
  name: string
  target: LlmTarget
}
