/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { LlmStateStatus } from './llmStateStatus'
import type { LlmTarget } from './llmTarget'

export interface LlmState {
  /** @nullable */
  error?: string | null
  status: LlmStateStatus
  target?: null | LlmTarget
}
