/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { LlmTargetKind } from './llmTargetKind'

export interface LlmTarget {
  kind: LlmTargetKind
  modelId: string
  /** @nullable */
  providerId?: string | null
}
