/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type MaskRole = (typeof MaskRole)[keyof typeof MaskRole]

export const MaskRole = {
  brushInpaint: 'brushInpaint',
  segment: 'segment',
  bubble: 'bubble',
} as const
