/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export type ModelLocationMode = (typeof ModelLocationMode)[keyof typeof ModelLocationMode]

export const ModelLocationMode = {
  use_existing: 'use_existing',
  move_existing: 'move_existing',
} as const
