/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface NamedFontPrediction {
  /** @minimum 0 */
  index: number
  /** @nullable */
  language?: string | null
  name: string
  probability: number
  serif: boolean
}
