/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { NodeDataPatch } from './nodeDataPatch'
import type { Transform } from './transform'

export interface NodePatch {
  data?: null | NodeDataPatch
  transform?: null | Transform
  /** @nullable */
  visible?: boolean | null
}
