/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface PagePatch {
  /**
   * @minimum 0
   * @nullable
   */
  height?: number | null
  /** @nullable */
  name?: string | null
  /**
   * @minimum 0
   * @nullable
   */
  width?: number | null
}
