/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type PipelineStatus =
  | {
      status: 'running'
    }
  | {
      status: 'completed'
    }
  | {
      status: 'cancelled'
    }
  | {
      reason: string
      status: 'failed'
    }
