/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface ProjectSummary {
  /** Stable identifier — the `.khrproj` directory basename (without the
  extension). Clients address projects by this. */
  id: string
  name: string
  /** Absolute filesystem path. Informational; clients never need to pass
  it back in — they use `id`. */
  path: string
  /**
     * Last modification time of the project directory on disk (ms since
  UNIX epoch). Used for "recent projects" ordering.
     * @minimum 0
     */
  updatedAtMs?: number
}
