/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface ProviderConfig {
  /**
     * Populated from credential storage on `load()`, never written to config.toml.
  Serializes as `"[REDACTED]"` in API responses.
     * @nullable
     */
  api_key?: string | null
  /** @nullable */
  base_url?: string | null
  id: string
}
