/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { BlobRef } from './blobRef'
import type { NodeId } from './nodeId'

export interface PutMaskResponse {
  blob: BlobRef
  node: NodeId
}
