/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ReadingOrder = (typeof ReadingOrder)[keyof typeof ReadingOrder]

export const ReadingOrder = {
  rtl: 'rtl',
  ltr: 'ltr',
  custom: 'custom',
} as const
