/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface Region {
  /** @minimum 0 */
  height: number
  /** @minimum 0 */
  width: number
  /** @minimum 0 */
  x: number
  /** @minimum 0 */
  y: number
}
