/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectMeta } from './projectMeta'
import type { ScenePages } from './scenePages'

export interface Scene {
  /** Pages in insertion order; `IndexMap` ordering *is* the page order. */
  pages: ScenePages
  project: ProjectMeta
}
