/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface SetModelLocationResponse {
  /** @minimum 0 */
  copiedBytes: number
  modelsPath: string
  restartRequired: boolean
  sourceRemoved: boolean
}
