/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { ModelLocationMode } from './modelLocationMode'

export interface SetModelLocationRequest {
  mode: ModelLocationMode
  path: string
}
