/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DownloadProgress } from './downloadProgress'
import type { JobSummary } from './jobSummary'

export interface SnapshotEvent {
  downloads: DownloadProgress[]
  jobs: JobSummary[]
}
