/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface StartDownloadResponse {
  /** Operation id. Reusing the package id keeps ids meaningful for clients
  watching progress events. */
  operationId: string
}
