/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface StartDownloadRequest {
  /**
   * Package id declared by `declare_hf_model_package!`, or a local LLM
   * operation id from `GET /llm/catalog` (for example `"llm:qwen3.5-2b"`).
   */
  modelId: string
}
