/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface StartDownloadRequest {
  /** Package id, as declared via `declare_hf_model_package!`
  (e.g. `"model:comic-text-detector:yolo-v5"`). */
  modelId: string
}
