/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface StorageSummary {
  customModelsPath: boolean
  dataPath: string
  /** @minimum 0 */
  downloadedLocalModels: number
  /** @minimum 0 */
  modelsBytes: number
  modelsPath: string
  /** @minimum 0 */
  temporaryBytes: number
}
