/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface TextStrokeStyle {
  color?: number[]
  enabled?: boolean
  /** @nullable */
  widthPx?: number | null
}
