/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

/**
 * Reading axis of a text block.
 */
export type TextDirection = (typeof TextDirection)[keyof typeof TextDirection]

export const TextDirection = {
  horizontal: 'horizontal',
  vertical: 'vertical',
} as const
