/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type TextAlign = (typeof TextAlign)[keyof typeof TextAlign]

export const TextAlign = {
  left: 'left',
  center: 'center',
  right: 'right',
} as const
